package it.polimi.ingsw.server.model.player;

public enum State {

    INITIAL_PHASE,
    SHOWING_RESOURCES_TO_MARKET,
    SHOWING_CARD_SHOP,
    SHOWING_LEADERS_INITIAL,
    SHOWING_LEADERS_FINAL,

    MIDDLE_PHASE,
    CHOOSING_CARD_PRODUCTION,
    SHOWING_PRODUCTIONS,
    CHOOSING_RESOURCE_FOR_PRODUCTION,
    CHOOSING_WHITEMARBLE_CONVERSION,
    SELECTING_RESOURCE_FOR_PRODUCTION,
    CHOOSING_POSITION_FOR_RESOURCES,

    FINAL_PHASE,
    IDLE,
    WINNING_STATE,
    LOSING_STATE,

}
